### ISSUE TITLE
Add the possibility to add buttons with links

### ISSUE THREAD

**Issue by seafoox** [algolia/documentation-editor#13]
Would be nice to be able to add buttons that could point to internal / external links

Not sure about the best way to do it in term of syntax, but it would be nice to be able to:
- Add several button on same line
- Have the possibility to change the color of each button, based on presets
- Have the possibility to add a small icon next to the button's label
## Proposal

**On centered button**

```
{buttonsGroup}
- [Lonely button](https://....){:target="_blank", :color="blue", :icon=""}
{/buttonsGroup}
```

![image](https://cloud.githubusercontent.com/assets/1101220/10224707/9781d828-685f-11e5-8b24-2819afc23eba.png)

**Two buttons on the same line**

```
{buttonsGroup}
- [First label](https://....){:target="_blank", :color="blue", :icon=""}
- [Second label](https://....){:target="_blank", :color="blue"}
{/buttonsGroup}
```

![image](https://cloud.githubusercontent.com/assets/1101220/10224676/66875626-685f-11e5-9df8-9b7354926251.png)

**Comment by Shipow** [comment]
button are for action, not links
