### ISSUE TITLE
 copy pasting < in code sections

### ISSUE THREAD

**Issue by kokliKo** [algolia/documentation-editor#16]
For some reason, I'm unable to copy paste the symbol "<" in the code sections anymore.
It only copy pastes the characters placed before the "<"

**Comment by redox** [comment]
Yes, that's a know limitation (https://github.com/algolia/documentation-editor/blob/master/app/assets/javascripts/documentation_editor/pages.js#L522-L552), need to work on improving the way the newlines/`<div>` are working.
