### ISSUE TITLE
Code editor adding lines randomly

### ISSUE THREAD

**Issue by kokliKo** [algolia/documentation-editor#17]
I have no clue why it's happening. Double checked, and I have no hidden characters, just 'return line' and 'space'.
It's been happening a lot, and applies randomly to one line or another.

![image](https://cloud.githubusercontent.com/assets/2853038/10711525/64d32c16-7a7e-11e5-93fb-00624751f9a0.png)
![image](https://cloud.githubusercontent.com/assets/2853038/10711527/6c377278-7a7e-11e5-8d7f-c7b4eea9e439.png)

**Comment by redox** [comment]
Probably related to #16
