### ISSUE TITLE
Graphical edit view does not display code differences between languages

### ISSUE THREAD

**Issue by PLNech** [algolia/documentation-editor#29]
When editing a code sample available in several languages, the graphical edit view does show the same code for every languages, even if they have different code samples (which you can see in the raw view and when previewing/publishing changes).
- Graphical view:
  ![sh|ruby code](https://cloud.githubusercontent.com/assets/1821404/13491334/2d9eb916-e132-11e5-996b-e49dc499bee2.png)
  ![sh|js code](https://cloud.githubusercontent.com/assets/1821404/13491337/2edbdcbe-e132-11e5-91da-36e4bcd2d1e3.png)  
- Raw view:
  ![raw code block](https://cloud.githubusercontent.com/assets/1821404/13491361/57e9c418-e132-11e5-9606-292b3b8edbf7.png)

Reproduced on Firefox 44.0.2 and Chrome Version 48.0.2564.116 (64-bit).

**Comment by redox** [comment]
Fixed in 1cf7bd9398a9533b7979ce7a8b8b4d5a1b8606bf
