### ISSUE TITLE
Docsearch dropdown not always working

### ISSUE THREAD

**Issue by pixelastic** [algolia/documentation-editor#32]
On https://www.algolia.com/doc/ruby, if I search for `browse` and select the second result, nothing happens:

![image](https://cloud.githubusercontent.com/assets/283419/15216936/93514d06-1859-11e6-9f9f-f68f6730b05b.png)

`Uncaught TypeError: Cannot read property 'top' of undefined`

``` javascript
$(window).on('hashchange', function(event) {
  $('html, body').scrollTop($(window.location.hash).offset().top - offset);
 });
```

**Comment by redox** [comment]
Arg, actually the index content is outdated and we're relying on finding the `$(window.location.hash)` DOM element in the page. Which is not true here, so `undefined` & fail. I'll run the re-indexing now.

**Comment by pixelastic** [comment]
Isn't it a DocSearch crawling?

**Comment by redox** [comment]
> Isn't it a DocSearch crawling?

Not yet :)
