### ISSUE TITLE
Increasing contrast on guide list

### ISSUE THREAD

**Issue by pixelastic** [algolia/documentation-editor#34]
On my not-a-mac-and-not-a-retina screen, the grey text under the various guide is close to unreadable because of the low contrast

![image](https://cloud.githubusercontent.com/assets/283419/15488239/4f953af6-2109-11e6-93f9-ae944654cff7.png)

And with `#4F5E7D`
![image](https://cloud.githubusercontent.com/assets/283419/15488275/8ba40e14-2109-11e6-8a38-3bf4cd530cc1.png)

**Comment by pixelastic** [comment]
This seems to be coming from `normalize`. I have no idea how to run it locally to see in which file I should put the override.

**Comment by redox** [comment]
This is something related to the CSS of the algolia.com website, not really about the documentation-editor. Could you move it there?

**Comment by pixelastic** [comment]
Argh, I never know where the boundaries are :). Sure, I'll move it there.
